server:
  port: ${PORT:8080}

spring:
  application:
    name: whattsapp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d7rn3omgkk3c738nufq0-a.oregon-postgres.render.com:5432/postgres_h0qf?sslmode=require
    username: postgres_h0qf_user
    password: xqfbLGrQd5TOQ63qyQDjW2rH2iGmJQZ3

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true